Mo/event controller
Patonymous/minispace pull request #19
Opened 2024-05-24 19:09 UTC by WildJellybear

2024-05-25 20:11 UTC, Patonymous requested changes
Made some comments

2024-05-25 20:11 UTC, Patonymous commented on Api/Controllers/EventsController.cs
> +        PriceFilter priceFilter = PriceFilter.Any, int minCapacityFilter = 0, int maxCapacityFilter = int.MaxValue, StartTimeFilter startTimeFilter = StartTimeFilter.Any, bool onlyAvailablePlace = fa
I think paging should handled by classes contributed in #16 (Paging and Paged), since it is repeatable code and should be unified across API. We need to decide if we want to request by page number (like in this code) or first item index (like in Paging class)

2024-05-25 20:11 UTC, Patonymous commented on Api/Controllers/EventsController.cs
No need for try-catch blocks here, exceptions are handled globally

2024-05-25 20:11 UTC, Patonymous commented on Api/DTO/Events/EventDto.cs
I don't think publication date should be in the response. In my opinion we should filter out Events that are before their publication date, maybe in EventService GetAll method

2024-05-25 20:11 UTC, Patonymous commented on Domain/Services/Implementations/EventService.cs
> +    public List<Event> GetAll() => uow.Repository<Event>().GetAll().ToList();
I would like it if we used AllowEveryone at the beginning of this method. It changes nothing when it comes to logic, but it makes it immediately obvious that this is the intention

2024-05-25 20:11 UTC, Patonymous commented on Api/DTO/Events/ListEventDto.cs
I'm not sure if we need this reduced version of EventDto. There's no hurt in sending all event data to Frontend. If it is too much for a list view, then Frontend will simply not show everything

2024-05-25 20:11 UTC, Patonymous commented on Api/Controllers/EventsController.cs
FYI, [Produces("application/json")] is also unnecessary, because it is the global default. (I was overly verbose when I wrote TestController). It does not cause any errors so you can just leave it

2024-05-26 08:06 UTC, WildJellybear commented on Api/DTO/Events/ListEventDto.cs
Kuba wanted reduced version

2024-05-26 08:08 UTC, WildJellybear commented on Api/DTO/Events/EventDto.cs
Yeah, I forgot to change it

2024-05-26 13:32 UTC, Luuxo77 commented on Api/Controllers/EventsController.cs
> +    }
I think it is enough to just call DeleteEvent, checking if event guid is wrong or if user is unauthorized is checked inside it already (by GetOrThrow method and AllowOnlyUser method).

2024-05-26 14:30 UTC, Patonymous commented on Api/DTO/Events/ListEventDto.cs
In that case let it be

2024-05-26 20:42 UTC, Patonymous reviewed
Some minor nitpicks

2024-05-26 20:42 UTC, Patonymous commented on Api/Controllers/EventsController.cs
>      public ActionResult CreateEvent(CreateEvent newEvent)
Description says "Create post", but the endpoint is "CreateEvent"

2024-05-26 20:42 UTC, Patonymous commented on Api/Controllers/EventsController.cs
>      public ActionResult DeleteEvent(Guid eventGuid)
Description says "Delete post", but the endpoint is "DeleteEvent"

2024-05-26 20:42 UTC, Patonymous commented on Api/DTO/Events/EventStateComparer.cs
> +    }
I'd rather we avoid warnings. I suggest to make function parameters nullable to satisfy IComparable<> interface and use x! and y!

2024-05-27 11:45 UTC, Patonymous approved these changes

2024-05-27 11:52 UTC, Patonymous approved these changes
I think it's ready to merge. One thing that comes to mind after a talk with @Luuxo77 is that you can put enum type in Dtos instead of string. In his PR #22 he added global JSON enum to string converter.

2024-05-27 12:30 UTC, Patonymous approved these changes

2024-05-27 12:34 UTC, merged